#/bin/sh -e
# Generated by scripts/configure.py
cd `dirname $0`/..
dotnet publish -c release -r win-x86
rm -rf SourceAFIS.FVC.FV.Matcher/bin/{submission,sourceafis-fvc-fv.zip}
mkdir -p SourceAFIS.FVC.FV.Matcher/bin/submission
cp ../sourceafis-fvc-fv-extractor/*/bin/Release/net*/win-x86/publish/* SourceAFIS.FVC.FV.Matcher/bin/submission/
cp */bin/Release/net*/win-x86/publish/* SourceAFIS.FVC.FV.Matcher/bin/submission/
cd SourceAFIS.FVC.FV.Matcher/bin/submission
zip ../sourceafis-fvc-fv.zip *
